// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Item {
    id: root

    property int currentPageIndex: 0

    // ── Logos palette ────────────────────────────────────────────────
    readonly property color colBg:      "#0f1117"
    readonly property color colSurface: "#1a1d27"
    readonly property color colSidebar: "#13151f"
    readonly property color colBorder:  "#2d3148"
    readonly property color colPrimary: "#7c6ef5"
    readonly property color colSuccess: "#3ecf8e"
    readonly property color colError:   "#e05252"
    readonly property color colText:    "#e8e9f0"
    readonly property color colMuted:   "#6b7280"
    readonly property int   radius:     12

    Connections {
        target: backend
        function onOperationSuccess(operation, txHash) {
            toast.show("\u2713 " + operation + (txHash ? " \u00b7 " + txHash.slice(0, 12) + "\u2026" : ""), root.colSuccess)
        }
        function onOperationError(operation, error) {
            toast.show("\u2717 " + operation + ": " + error, root.colError)
        }
    }

    Rectangle {
        anchors.fill: parent
        color: root.colBg

        // ── Sidebar ──────────────────────────────────────────────────────
        Rectangle {
            id: sidebar
            anchors { left: parent.left; top: parent.top; bottom: parent.bottom }
            width: 200
            color: root.colSidebar

            ColumnLayout {
                anchors.fill: parent
                spacing: 0

                RowLayout {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 52
                    Layout.leftMargin: 16; Layout.rightMargin: 8
                    Text {
                        text: "Lez Multisig"
                        color: root.colText
                        font.pixelSize: 15; font.bold: true
                        Layout.fillWidth: true
                    }
                    BusyIndicator {
                        running: backend.busy; visible: running
                        implicitWidth: 24; implicitHeight: 24
                    }
                }

                Rectangle { Layout.fillWidth: true; height: 1; color: root.colBorder }

                ScrollView {
                    Layout.fillWidth: true
                    Layout.fillHeight: true
                    clip: true
                    contentWidth: sidebar.width

                    Column {
                        width: sidebar.width

                        Text {
                            x: 12; width: sidebar.width - 12; height: 28
                            text: "ACCOUNTS"
                            color: root.colMuted
                            font.pixelSize: 10
                            font.letterSpacing: 1
                            font.bold: true
                            verticalAlignment: Text.AlignVCenter
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 0
                            background: Rectangle {
                                color: root.currentPageIndex === 0
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Multisig State"
                                color: root.currentPageIndex === 0 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 1
                            background: Rectangle {
                                color: root.currentPageIndex === 1
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Proposal"
                                color: root.currentPageIndex === 1 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        Rectangle {
                            width: sidebar.width
                            height: 1
                            color: root.colBorder
                        }
                        Text {
                            x: 12; width: sidebar.width - 12; height: 28
                            text: "INSTRUCTIONS"
                            color: root.colMuted
                            font.pixelSize: 10
                            font.letterSpacing: 1
                            font.bold: true
                            verticalAlignment: Text.AlignVCenter
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 2
                            background: Rectangle {
                                color: root.currentPageIndex === 2
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Create Multisig"
                                color: root.currentPageIndex === 2 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 3
                            background: Rectangle {
                                color: root.currentPageIndex === 3
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Propose"
                                color: root.currentPageIndex === 3 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 4
                            background: Rectangle {
                                color: root.currentPageIndex === 4
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Approve"
                                color: root.currentPageIndex === 4 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 5
                            background: Rectangle {
                                color: root.currentPageIndex === 5
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Reject"
                                color: root.currentPageIndex === 5 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 6
                            background: Rectangle {
                                color: root.currentPageIndex === 6
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Execute"
                                color: root.currentPageIndex === 6 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 7
                            background: Rectangle {
                                color: root.currentPageIndex === 7
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Propose Add Member"
                                color: root.currentPageIndex === 7 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 8
                            background: Rectangle {
                                color: root.currentPageIndex === 8
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Propose Remove Member"
                                color: root.currentPageIndex === 8 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 9
                            background: Rectangle {
                                color: root.currentPageIndex === 9
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Propose Change Threshold"
                                color: root.currentPageIndex === 9 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                        Rectangle {
                            width: sidebar.width
                            height: 1
                            color: root.colBorder
                        }
                        Text {
                            x: 12; width: sidebar.width - 12; height: 28
                            text: "SETTINGS"
                            color: root.colMuted
                            font.pixelSize: 10
                            font.letterSpacing: 1
                            font.bold: true
                            verticalAlignment: Text.AlignVCenter
                        }
                        ItemDelegate {
                            width: sidebar.width
                            height: 40
                            onClicked: root.currentPageIndex = 10
                            background: Rectangle {
                                color: root.currentPageIndex === 10
                                       ? Qt.rgba(0.49, 0.43, 0.96, 0.15) : "transparent"
                            }
                            contentItem: Text {
                                text: "Settings"
                                color: root.currentPageIndex === 10 ? root.colPrimary : root.colText
                                font.pixelSize: 13
                                leftPadding: 16
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }
            }
        }

        // ── Content pages ────────────────────────────────────────────────
        StackLayout {
            id: pageStack
            anchors { left: sidebar.right; right: parent.right; top: parent.top; bottom: parent.bottom }
            currentIndex: root.currentPageIndex

            Item {
                id: pageFetchMultisigState
                Rectangle { anchors.fill: parent; color: root.colSurface }
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageFetchMultisigState.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        RowLayout {
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            Text {
                                text: "Multisig State"
                                color: root.colText
                                font.pixelSize: 18; font.bold: true
                                Layout.fillWidth: true
                            }
                            Button {
                                text: "\u21ba"
                                onClicked: backend.fetchMultisigState(fetchMultisigState_create_key_f.text)
                                background: Rectangle {
                                    color: root.colSurface; border.color: root.colBorder; radius: root.radius / 2
                                }
                                contentItem: Text {
                                    text: parent.text; color: root.colMuted
                                    horizontalAlignment: Text.AlignHCenter
                                    verticalAlignment: Text.AlignVCenter
                                }
                            }
                        }

                        TextField {
                            id: fetchMultisigState_create_key_f
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "createKey (seed)"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Repeater {
                            model: Object.keys(backend.multisigState)
                            delegate: RowLayout {
                                Layout.fillWidth: true
                                Layout.leftMargin: 24
                                Layout.rightMargin: 8
                                Text { text: modelData + ":"; color: root.colMuted; font.pixelSize: 12; Layout.preferredWidth: 140 }
                                Text {
                                    property var _v: backend.multisigState[modelData]
                                    text: Array.isArray(_v) ? _v.join("\n") : (_v ?? "")
                                    color: root.colText; font.pixelSize: 12
                                    wrapMode: Text.WrapAtWordBoundaryOrAnywhere
                                    Layout.fillWidth: true
                                }
                                Button {
                                    implicitWidth: 28; implicitHeight: 28
                                    property var _v: backend.multisigState[modelData]
                                    onClicked: clipHelper.copyText(Array.isArray(_v) ? _v.join("\n") : (_v ?? ""))
                                    background: Item {}
                                    contentItem: Text {
                                        text: "\u29C9"
                                        color: root.colMuted
                                        font.pixelSize: 14
                                        horizontalAlignment: Text.AlignHCenter
                                        verticalAlignment: Text.AlignVCenter
                                    }
                                }
                            }
                        }

                        Text {
                            visible: Object.keys(backend.multisigState).length === 0
                            text: "No data — press \u21ba to fetch."
                            color: root.colMuted; font.pixelSize: 12
                            Layout.leftMargin: 24
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageFetchProposal
                Rectangle { anchors.fill: parent; color: root.colSurface }
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageFetchProposal.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        RowLayout {
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            Text {
                                text: "Proposal"
                                color: root.colText
                                font.pixelSize: 18; font.bold: true
                                Layout.fillWidth: true
                            }
                            Button {
                                text: "\u21ba"
                                onClicked: backend.fetchProposal(fetchProposal_create_key_f.text, parseInt(fetchProposal_proposal_index_f.text))
                                background: Rectangle {
                                    color: root.colSurface; border.color: root.colBorder; radius: root.radius / 2
                                }
                                contentItem: Text {
                                    text: parent.text; color: root.colMuted
                                    horizontalAlignment: Text.AlignHCenter
                                    verticalAlignment: Text.AlignVCenter
                                }
                            }
                        }

                        TextField {
                            id: fetchProposal_create_key_f
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "createKey (seed)"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: fetchProposal_proposal_index_f
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "proposalIndex (seed)"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Repeater {
                            model: Object.keys(backend.proposal)
                            delegate: RowLayout {
                                Layout.fillWidth: true
                                Layout.leftMargin: 24
                                Layout.rightMargin: 8
                                Text { text: modelData + ":"; color: root.colMuted; font.pixelSize: 12; Layout.preferredWidth: 140 }
                                Text {
                                    property var _v: backend.proposal[modelData]
                                    text: Array.isArray(_v) ? _v.join("\n") : (_v ?? "")
                                    color: root.colText; font.pixelSize: 12
                                    wrapMode: Text.WrapAtWordBoundaryOrAnywhere
                                    Layout.fillWidth: true
                                }
                                Button {
                                    implicitWidth: 28; implicitHeight: 28
                                    property var _v: backend.proposal[modelData]
                                    onClicked: clipHelper.copyText(Array.isArray(_v) ? _v.join("\n") : (_v ?? ""))
                                    background: Item {}
                                    contentItem: Text {
                                        text: "\u29C9"
                                        color: root.colMuted
                                        font.pixelSize: 14
                                        horizontalAlignment: Text.AlignHCenter
                                        verticalAlignment: Text.AlignVCenter
                                    }
                                }
                            }
                        }

                        Text {
                            visible: Object.keys(backend.proposal).length === 0
                            text: "No data — press \u21ba to fetch."
                            color: root.colMuted; font.pixelSize: 12
                            Layout.leftMargin: 24
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageCreateMultisig
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageCreateMultisig.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Create Multisig"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: create_multisig_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "threshold"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: create_multisig_thresholdf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            validator: IntValidator { bottom: 0; top: 255 }
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "members"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextArea {
                            id: create_multisig_membersf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            implicitHeight: 72
                            placeholderText: "members (one per line)"
                            color: root.colText; wrapMode: TextArea.Wrap
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Create Multisig"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.createMultisig(create_multisig_create_keyf.text, parseInt(create_multisig_thresholdf.text), create_multisig_membersf.text.split("\n").map(function(s){ return s.trim() }).filter(function(s){ return s.length > 0 }))
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pagePropose
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pagePropose.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Propose"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "proposerId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_proposer_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "targetProgramId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_target_program_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "value"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "targetInstructionData"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextArea {
                            id: propose_target_instruction_dataf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            implicitHeight: 72
                            placeholderText: "targetInstructionData (one per line)"
                            color: root.colText; wrapMode: TextArea.Wrap
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "targetAccountCount"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_target_account_countf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            validator: IntValidator { bottom: 0; top: 255 }
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "pdaSeeds"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextArea {
                            id: propose_pda_seedsf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            implicitHeight: 72
                            placeholderText: "pdaSeeds (one per line)"
                            color: root.colText; wrapMode: TextArea.Wrap
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "authorizedIndices"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextArea {
                            id: propose_authorized_indicesf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            implicitHeight: 72
                            placeholderText: "authorizedIndices (one per line)"
                            color: root.colText; wrapMode: TextArea.Wrap
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Propose"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.propose(propose_proposer_idf.text, propose_target_program_idf.text, propose_target_instruction_dataf.text.split("\n").map(function(s){ return s.trim() }).filter(function(s){ return s.length > 0 }), parseInt(propose_target_account_countf.text), propose_pda_seedsf.text.split("\n").map(function(s){ return s.trim() }).filter(function(s){ return s.length > 0 }), propose_authorized_indicesf.text.split("\n").map(function(s){ return s.trim() }).filter(function(s){ return s.length > 0 }), propose_create_keyf.text, propose_proposal_indexf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageApprove
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageApprove.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Approve"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "approverId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: approve_approver_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: approve_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: approve_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Approve"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.approve(approve_approver_idf.text, approve_proposal_indexf.text, approve_create_keyf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageReject
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageReject.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Reject"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "rejectorId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: reject_rejector_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: reject_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: reject_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Reject"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.reject(reject_rejector_idf.text, reject_proposal_indexf.text, reject_create_keyf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageExecute
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageExecute.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Execute"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "executorId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: execute_executor_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: execute_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: execute_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Execute"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.execute(execute_executor_idf.text, execute_proposal_indexf.text, execute_create_keyf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageProposeAddMember
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageProposeAddMember.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Propose Add Member"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "proposerId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_add_member_proposer_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "newMember"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_add_member_new_memberf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_add_member_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_add_member_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Propose Add Member"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeAddMember(propose_add_member_proposer_idf.text, propose_add_member_new_memberf.text, propose_add_member_create_keyf.text, propose_add_member_proposal_indexf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageProposeRemoveMember
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageProposeRemoveMember.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Propose Remove Member"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "proposerId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_remove_member_proposer_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "member"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_remove_member_memberf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_remove_member_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_remove_member_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Propose Remove Member"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeRemoveMember(propose_remove_member_proposer_idf.text, propose_remove_member_memberf.text, propose_remove_member_create_keyf.text, propose_remove_member_proposal_indexf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageProposeChangeThreshold
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageProposeChangeThreshold.width; spacing: 12

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Propose Change Threshold"
                            color: root.colText
                            font.pixelSize: 18
                            font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "proposerId"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_change_threshold_proposer_idf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "newThreshold"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_change_threshold_new_thresholdf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            validator: IntValidator { bottom: 0; top: 255 }
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "createKey"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_change_threshold_create_keyf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "base58 or 0x… hex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "proposalIndex"
                            color: root.colMuted
                            font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            id: propose_change_threshold_proposal_indexf
                            Layout.fillWidth: true
                            Layout.leftMargin: 24
                            Layout.rightMargin: 24
                            placeholderText: "integer (≥ 0)"
                            inputMethodHints: Qt.ImhDigitsOnly
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Propose Change Threshold"
                            enabled: !backend.busy
                            Layout.rightMargin: 24; Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeChangeThreshold(propose_change_threshold_proposer_idf.text, parseInt(propose_change_threshold_new_thresholdf.text), propose_change_threshold_create_keyf.text, propose_change_threshold_proposal_indexf.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text; color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

            Item {
                id: pageSettings
                Rectangle { anchors.fill: parent; color: root.colSurface }
                ScrollView {
                    anchors.fill: parent; clip: true
                    contentWidth: availableWidth

                    ColumnLayout {
                        width: pageSettings.width; spacing: 16

                        Item { Layout.fillWidth: true; height: 24 }

                        Text {
                            text: "Settings"
                            color: root.colText; font.pixelSize: 18; font.bold: true
                            Layout.leftMargin: 24
                        }

                        Text {
                            text: "Wallet Path"
                            color: root.colMuted; font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            text: backend.walletPath
                            onEditingFinished: backend.setWalletPath(text)
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            color: root.colText; placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface; border.color: root.colBorder; radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "Sequencer URL"
                            color: root.colMuted; font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            text: backend.sequencerUrl
                            onEditingFinished: backend.setSequencerUrl(text)
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            color: root.colText; placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface; border.color: root.colBorder; radius: root.radius / 2
                            }
                        }

                        Text {
                            text: "Program ID (hex)"
                            color: root.colMuted; font.pixelSize: 11
                            Layout.leftMargin: 24
                        }
                        TextField {
                            text: backend.programIdHex
                            onEditingFinished: backend.setProgramIdHex(text)
                            Layout.fillWidth: true
                            Layout.leftMargin: 24; Layout.rightMargin: 24
                            color: root.colText; placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colSurface; border.color: root.colBorder; radius: root.radius / 2
                            }
                        }

                        Item { Layout.fillWidth: true; height: 80 }
                    }
                }
            }

        }

        Rectangle {
            id: toast
            anchors { bottom: parent.bottom; horizontalCenter: parent.horizontalCenter; bottomMargin: 24 }
            width: toastText.implicitWidth + 32; height: 40
            radius: root.radius
            color: root.colSurface
            opacity: 0; visible: opacity > 0

            function show(msg, col) {
                toastText.text = msg
                toast.color = col
                toast.opacity = 1
                toastTimer.restart()
            }

            Text {
                id: toastText
                anchors.centerIn: parent
                color: root.colText
                font.pixelSize: 13
            }

            Behavior on opacity { NumberAnimation { duration: 200 } }

            Timer {
                id: toastTimer
                interval: 3000
                onTriggered: toast.opacity = 0
            }
        }
    }
    TextEdit {
        id: clipHelper; visible: false
        function copyText(t) { clipHelper.text = t; selectAll(); copy() }
    }

}
