// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

Item {
    id: root

    // ── Logos palette ─────────────────────────────────────────────────────
    readonly property color colBg:      "#0f1117"
    readonly property color colSurface: "#1a1d27"
    readonly property color colBorder:  "#2d3148"
    readonly property color colPrimary: "#7c6ef5"
    readonly property color colSuccess: "#3ecf8e"
    readonly property color colError:   "#e05252"
    readonly property color colText:    "#e8e9f0"
    readonly property color colMuted:   "#6b7280"
    readonly property int   radius:     12

    Connections {
        target: backend
        function onOperationSuccess(operation, txHash) {
            toast.show("\u2713 " + operation + " \u00b7 " + txHash.slice(0, 12) + "\u2026", root.colSuccess)
        }
        function onOperationError(operation, error) {
            toast.show("\u2717 " + operation + ": " + error, root.colError)
        }
    }

    Rectangle {
        anchors.fill: parent
        color: root.colBg

        ScrollView {
            id: scrollView
            anchors.fill: parent
            clip: true

            ColumnLayout {
                width: scrollView.width
                spacing: 12
                leftPadding: 16; rightPadding: 16
                topPadding: 16; bottomPadding: 80

                BusyIndicator {
                    running: backend.busy
                    visible: running
                    Layout.alignment: Qt.AlignHCenter
                }

                // ── CreateMultisig ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_create_multisig.implicitHeight + 32

                    ColumnLayout {
                        id: col_create_multisig
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "CreateMultisig"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: create_multisig_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: create_multisig_threshold_f
                            Layout.fillWidth: true
                            placeholderText: "threshold"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: create_multisig_members_f
                            Layout.fillWidth: true
                            placeholderText: "members"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "CreateMultisig"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.createMultisig(create_multisig_create_key_f.text, parseInt(create_multisig_threshold_f.text), create_multisig_members_f.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── Propose ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_propose.implicitHeight + 32

                    ColumnLayout {
                        id: col_propose
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "Propose"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: propose_proposer_id_f
                            Layout.fillWidth: true
                            placeholderText: "proposerId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_target_program_id_f
                            Layout.fillWidth: true
                            placeholderText: "targetProgramId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_target_instruction_data_f
                            Layout.fillWidth: true
                            placeholderText: "targetInstructionData"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_target_account_count_f
                            Layout.fillWidth: true
                            placeholderText: "targetAccountCount"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_pda_seeds_f
                            Layout.fillWidth: true
                            placeholderText: "pdaSeeds"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_authorized_indices_f
                            Layout.fillWidth: true
                            placeholderText: "authorizedIndices"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Propose"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.propose(propose_proposer_id_f.text, propose_target_program_id_f.text, propose_target_instruction_data_f.text, parseInt(propose_target_account_count_f.text), propose_pda_seeds_f.text, propose_authorized_indices_f.text, propose_create_key_f.text, parseInt(propose_proposal_index_f.text))
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── Approve ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_approve.implicitHeight + 32

                    ColumnLayout {
                        id: col_approve
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "Approve"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: approve_approver_id_f
                            Layout.fillWidth: true
                            placeholderText: "approverId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: approve_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: approve_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Approve"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.approve(approve_approver_id_f.text, parseInt(approve_proposal_index_f.text), approve_create_key_f.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── Reject ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_reject.implicitHeight + 32

                    ColumnLayout {
                        id: col_reject
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "Reject"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: reject_rejector_id_f
                            Layout.fillWidth: true
                            placeholderText: "rejectorId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: reject_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: reject_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Reject"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.reject(reject_rejector_id_f.text, parseInt(reject_proposal_index_f.text), reject_create_key_f.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── Execute ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_execute.implicitHeight + 32

                    ColumnLayout {
                        id: col_execute
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "Execute"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: execute_executor_id_f
                            Layout.fillWidth: true
                            placeholderText: "executorId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: execute_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: execute_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "Execute"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.execute(execute_executor_id_f.text, parseInt(execute_proposal_index_f.text), execute_create_key_f.text)
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── ProposeAddMember ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_propose_add_member.implicitHeight + 32

                    ColumnLayout {
                        id: col_propose_add_member
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "ProposeAddMember"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: propose_add_member_proposer_id_f
                            Layout.fillWidth: true
                            placeholderText: "proposerId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_add_member_new_member_f
                            Layout.fillWidth: true
                            placeholderText: "newMember"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_add_member_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_add_member_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "ProposeAddMember"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeAddMember(propose_add_member_proposer_id_f.text, propose_add_member_new_member_f.text, propose_add_member_create_key_f.text, parseInt(propose_add_member_proposal_index_f.text))
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── ProposeRemoveMember ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_propose_remove_member.implicitHeight + 32

                    ColumnLayout {
                        id: col_propose_remove_member
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "ProposeRemoveMember"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: propose_remove_member_proposer_id_f
                            Layout.fillWidth: true
                            placeholderText: "proposerId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_remove_member_member_f
                            Layout.fillWidth: true
                            placeholderText: "member"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_remove_member_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_remove_member_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "ProposeRemoveMember"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeRemoveMember(propose_remove_member_proposer_id_f.text, propose_remove_member_member_f.text, propose_remove_member_create_key_f.text, parseInt(propose_remove_member_proposal_index_f.text))
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

                // ── ProposeChangeThreshold ──────────────────────────────────────────────
                Rectangle {
                    Layout.fillWidth: true
                    color: root.colSurface
                    radius: root.radius
                    implicitHeight: col_propose_change_threshold.implicitHeight + 32

                    ColumnLayout {
                        id: col_propose_change_threshold
                        anchors { left: parent.left; right: parent.right; margins: 16 }
                        y: 16; spacing: 8

                        Text {
                            text: "ProposeChangeThreshold"
                            color: root.colText
                            font.pixelSize: 14; font.bold: true
                        }

                        TextField {
                            id: propose_change_threshold_proposer_id_f
                            Layout.fillWidth: true
                            placeholderText: "proposerId"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_change_threshold_new_threshold_f
                            Layout.fillWidth: true
                            placeholderText: "newThreshold"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_change_threshold_create_key_f
                            Layout.fillWidth: true
                            placeholderText: "createKey"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        TextField {
                            id: propose_change_threshold_proposal_index_f
                            Layout.fillWidth: true
                            placeholderText: "proposalIndex"
                            color: root.colText
                            placeholderTextColor: root.colMuted
                            background: Rectangle {
                                color: root.colBg
                                border.color: root.colBorder
                                radius: root.radius / 2
                            }
                        }

                        Button {
                            text: backend.busy ? "\u2026" : "ProposeChangeThreshold"
                            enabled: !backend.busy
                            Layout.alignment: Qt.AlignRight
                            onClicked: backend.proposeChangeThreshold(propose_change_threshold_proposer_id_f.text, parseInt(propose_change_threshold_new_threshold_f.text), propose_change_threshold_create_key_f.text, parseInt(propose_change_threshold_proposal_index_f.text))
                            background: Rectangle {
                                color: parent.down ? Qt.darker(root.colPrimary, 1.2) : root.colPrimary
                                radius: root.radius / 2
                                opacity: parent.enabled ? 1.0 : 0.5
                            }
                            contentItem: Text {
                                text: parent.text
                                color: root.colText
                                horizontalAlignment: Text.AlignHCenter
                                verticalAlignment: Text.AlignVCenter
                            }
                        }
                    }
                }

            }
        }

        Rectangle {
            id: toast
            anchors { bottom: parent.bottom; horizontalCenter: parent.horizontalCenter; bottomMargin: 24 }
            width: toastText.implicitWidth + 32; height: 40
            radius: root.radius
            color: root.colSurface
            opacity: 0; visible: opacity > 0

            function show(msg, col) {
                toastText.text = msg
                toast.color = col
                toast.opacity = 1
                toastTimer.restart()
            }

            Text {
                id: toastText
                anchors.centerIn: parent
                color: root.colText
                font.pixelSize: 13
            }

            Behavior on opacity { NumberAnimation { duration: 200 } }

            Timer {
                id: toastTimer
                interval: 3000
                onTriggered: toast.opacity = 0
            }
        }
    }
}
