// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#include "LezMultisigPlugin.h"
#include "LezMultisigBackend.h"

#include <QQmlContext>
#include <QQmlEngine>
#include <QQuickWidget>
#include <QUrl>
#include <cstdlib>

LezMultisigPlugin::LezMultisigPlugin(QObject* parent) : QObject(parent) {}
LezMultisigPlugin::~LezMultisigPlugin() = default;

void LezMultisigPlugin::initLogos(LogosAPI* api) {
	m_api = api;
}

QWidget* LezMultisigPlugin::createWidget(LogosAPI* api) {
	if (api) m_api = api;
	if (!m_backend)
		m_backend = new LezMultisigBackend(m_api, this);
	auto* view = new QQuickWidget();
	view->engine()->rootContext()->setContextProperty("backend", m_backend);
	view->setResizeMode(QQuickWidget::SizeRootObjectToView);
	const char* qmlPath = std::getenv("QML_PATH");
	if (qmlPath)
		view->setSource(QUrl::fromLocalFile(QString::fromUtf8(qmlPath) + "/Main.qml"));
	else
		view->setSource(QUrl("qrc:/qml/Main.qml"));
	return view;
}

void LezMultisigPlugin::destroyWidget(QWidget* widget) {
	delete m_backend;
	m_backend = nullptr;
	delete widget;
}
