// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#include "LezMultisigBackend.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMetaObject>
#include <QThreadPool>
#include <QtConcurrent/QtConcurrent>

extern "C" {
    char* multisig_program_create_multisig(const char* args_json);
    char* multisig_program_propose(const char* args_json);
    char* multisig_program_approve(const char* args_json);
    char* multisig_program_reject(const char* args_json);
    char* multisig_program_execute(const char* args_json);
    char* multisig_program_propose_add_member(const char* args_json);
    char* multisig_program_propose_remove_member(const char* args_json);
    char* multisig_program_propose_change_threshold(const char* args_json);
    void  multisig_program_free_string(char* s);
    // NOTE: lez_multisig_program_id() uses the stable wrapper prefix (baked-in at compile time)
    char* lez_multisig_program_id();
}

// ── Construction ──────────────────────────────────────────────────────────

LezMultisigBackend::LezMultisigBackend(LogosAPI* /*api*/, QObject* parent)
    : QObject(parent)
    , m_walletPath(qEnvironmentVariable("NSSA_WALLET_HOME_DIR", ".scaffold/wallet"))
    , m_sequencerUrl(qEnvironmentVariable("NSSA_SEQUENCER_URL", "http://127.0.0.1:3040"))
{
    // Priority: explicit env var > baked-in compile-time constant
    m_programIdHex = qEnvironmentVariable("LEZ_MULTISIG_PROGRAM_ID_HEX");
    if (m_programIdHex.isEmpty()) {
        char* raw = lez_multisig_program_id();
        if (raw) {
            m_programIdHex = QJsonDocument::fromJson(QByteArray(raw))
                                 .object().value("program_id_hex").toString();
            multisig_program_free_string(raw);
        }
    }
}

LezMultisigBackend::~LezMultisigBackend() = default;

// ── Helpers ──────────────────────────────────────────────────────────────

QJsonObject LezMultisigBackend::baseArgs() const {
    return QJsonObject{
        {"wallet_path",    m_walletPath},
        {"sequencer_url",  m_sequencerUrl},
        {"program_id_hex", m_programIdHex},
    };
}

QString LezMultisigBackend::callFfi(FfiFn fn, const QJsonObject& args) {
    QByteArray json = QJsonDocument(args).toJson(QJsonDocument::Compact);
    char* raw = fn(json.constData());
    if (!raw) return R"({"success":false,"error":"null return from FFI"})";
    QString result = QString::fromUtf8(raw);
    multisig_program_free_string(raw);
    return result;
}

void LezMultisigBackend::dispatchFfi(const QString& operation, std::function<QString()> fn) {
    if (m_busy) return;
    m_busy = true;
    emit busyChanged();

    auto* watcher = new QFutureWatcher<QString>(this);
    connect(watcher, &QFutureWatcher<QString>::finished, this, [this, watcher, operation]() {
        handleFfiResult(operation, watcher->result());
        watcher->deleteLater();
        m_busy = false;
        emit busyChanged();
    });
    watcher->setFuture(QtConcurrent::run(fn));
}

void LezMultisigBackend::handleFfiResult(const QString& operation, const QString& result) {
    QJsonObject obj = QJsonDocument::fromJson(result.toUtf8()).object();

    if (!obj.value("success").toBool()) {
        m_lastError = obj.value("error").toString(result);
        emit lastErrorChanged();
        emit operationError(operation, m_lastError);
        return;
    }

    m_lastError.clear();
    emit lastErrorChanged();

    if (obj.contains("tx_hash")) {
        m_lastTxHash = obj.value("tx_hash").toString();
        emit lastTxHashChanged();
        emit operationSuccess(operation, m_lastTxHash);
    }
}

// ── Instructions ─────────────────────────────────────────────────────────

void LezMultisigBackend::createMultisig(const QString& createKey, quint32 threshold, const QVariantList& members) {
    QJsonObject args = baseArgs();
    args["create_key"] = createKey;
    args["threshold"] = static_cast<int>(threshold);
    {
        QJsonArray _arr;
        for (const auto& _s : members) _arr.append(_s.toString());
        args["members"] = _arr;
    }
    dispatchFfi("create_multisig", [this, args]() {
        return callFfi(multisig_program_create_multisig, args);
    });
}

void LezMultisigBackend::propose(const QString& proposerId, const QString& targetProgramId, const QVariantList& targetInstructionData, quint32 targetAccountCount, const QVariantList& pdaSeeds, const QVariantList& authorizedIndices, const QString& createKey, quint64 proposalIndex) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["target_program_id"] = targetProgramId;
    {
        QJsonArray _arr;
        for (const auto& _s : targetInstructionData) _arr.append(_s.toString());
        args["target_instruction_data"] = _arr;
    }
    args["target_account_count"] = static_cast<int>(targetAccountCount);
    {
        QJsonArray _arr;
        for (const auto& _s : pdaSeeds) _arr.append(_s.toString());
        args["pda_seeds"] = _arr;
    }
    {
        QJsonArray _arr;
        for (const auto& _s : authorizedIndices) _arr.append(_s.toString());
        args["authorized_indices"] = _arr;
    }
    args["create_key"] = createKey;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    dispatchFfi("propose", [this, args]() {
        return callFfi(multisig_program_propose, args);
    });
}

void LezMultisigBackend::approve(const QString& approverId, quint64 proposalIndex, const QString& createKey) {
    QJsonObject args = baseArgs();
    args["approver"] = approverId;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    args["create_key"] = createKey;
    dispatchFfi("approve", [this, args]() {
        return callFfi(multisig_program_approve, args);
    });
}

void LezMultisigBackend::reject(const QString& rejectorId, quint64 proposalIndex, const QString& createKey) {
    QJsonObject args = baseArgs();
    args["rejector"] = rejectorId;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    args["create_key"] = createKey;
    dispatchFfi("reject", [this, args]() {
        return callFfi(multisig_program_reject, args);
    });
}

void LezMultisigBackend::execute(const QString& executorId, quint64 proposalIndex, const QString& createKey) {
    QJsonObject args = baseArgs();
    args["executor"] = executorId;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    args["create_key"] = createKey;
    dispatchFfi("execute", [this, args]() {
        return callFfi(multisig_program_execute, args);
    });
}

void LezMultisigBackend::proposeAddMember(const QString& proposerId, const QString& newMember, const QString& createKey, quint64 proposalIndex) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["new_member"] = newMember;
    args["create_key"] = createKey;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    dispatchFfi("propose_add_member", [this, args]() {
        return callFfi(multisig_program_propose_add_member, args);
    });
}

void LezMultisigBackend::proposeRemoveMember(const QString& proposerId, const QString& member, const QString& createKey, quint64 proposalIndex) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["member"] = member;
    args["create_key"] = createKey;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    dispatchFfi("propose_remove_member", [this, args]() {
        return callFfi(multisig_program_propose_remove_member, args);
    });
}

void LezMultisigBackend::proposeChangeThreshold(const QString& proposerId, quint32 newThreshold, const QString& createKey, quint64 proposalIndex) {
    QJsonObject args = baseArgs();
    args["proposer"] = proposerId;
    args["new_threshold"] = static_cast<int>(newThreshold);
    args["create_key"] = createKey;
    args["proposal_index"] = static_cast<qint64>(proposalIndex);
    dispatchFfi("propose_change_threshold", [this, args]() {
        return callFfi(multisig_program_propose_change_threshold, args);
    });
}

