// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
#pragma once

#include <functional>
#include <QFutureWatcher>
#include <QJsonArray>
#include <QJsonObject>
#include <QObject>
#include <QString>
#include <QStringList>
#include <QTimer>
#include <QVariantList>
#include <QVariantMap>

class LogosAPI;

class LezMultisigBackend : public QObject {
    Q_OBJECT

    // ── Async status ──────────────────────────────────────────────────────
    Q_PROPERTY(bool       busy       READ busy       NOTIFY busyChanged)
    Q_PROPERTY(QString    lastError  READ lastError  NOTIFY lastErrorChanged)
    Q_PROPERTY(QString    lastTxHash READ lastTxHash NOTIFY lastTxHashChanged)
    Q_PROPERTY(QVariantMap lastResult READ lastResult NOTIFY lastResultChanged)

    // ── Configuration ────────────────────────────────────────────────────
    Q_PROPERTY(QString walletPath   READ walletPath   WRITE setWalletPath   NOTIFY walletPathChanged)
    Q_PROPERTY(QString sequencerUrl READ sequencerUrl WRITE setSequencerUrl NOTIFY sequencerUrlChanged)
    Q_PROPERTY(QString programIdHex READ programIdHex WRITE setProgramIdHex NOTIFY programIdHexChanged)

public:
    explicit LezMultisigBackend(LogosAPI* api, QObject* parent = nullptr);
    ~LezMultisigBackend() override;

    bool       busy()       const { return m_busy; }
    QString    lastError()  const { return m_lastError; }
    QString    lastTxHash() const { return m_lastTxHash; }
    QVariantMap lastResult() const { return m_lastResult; }

    QString walletPath()   const { return m_walletPath; }
    QString sequencerUrl() const { return m_sequencerUrl; }
    QString programIdHex() const { return m_programIdHex; }
    Q_INVOKABLE void setWalletPath(const QString& v);
    Q_INVOKABLE void setSequencerUrl(const QString& v);
    Q_INVOKABLE void setProgramIdHex(const QString& v);

    // ── Instructions ──────────────────────────────────────────────────────
    Q_INVOKABLE void createMultisig(const QString& createKey, quint32 threshold, const QVariantList& members);
    Q_INVOKABLE void propose(const QString& proposerId, const QString& targetProgramId, const QVariantList& targetInstructionData, quint32 targetAccountCount, const QVariantList& pdaSeeds, const QVariantList& authorizedIndices, const QString& createKey, quint64 proposalIndex);
    Q_INVOKABLE void approve(const QString& approverId, quint64 proposalIndex, const QString& createKey);
    Q_INVOKABLE void reject(const QString& rejectorId, quint64 proposalIndex, const QString& createKey);
    Q_INVOKABLE void execute(const QString& executorId, quint64 proposalIndex, const QString& createKey);
    Q_INVOKABLE void proposeAddMember(const QString& proposerId, const QString& newMember, const QString& createKey, quint64 proposalIndex);
    Q_INVOKABLE void proposeRemoveMember(const QString& proposerId, const QString& member, const QString& createKey, quint64 proposalIndex);
    Q_INVOKABLE void proposeChangeThreshold(const QString& proposerId, quint32 newThreshold, const QString& createKey, quint64 proposalIndex);

signals:
    void busyChanged();
    void lastErrorChanged();
    void lastTxHashChanged();
    void lastResultChanged();
    void operationSuccess(const QString& operation, const QString& txHash);
    void operationError(const QString& operation, const QString& error);
    void walletPathChanged();
    void sequencerUrlChanged();
    void programIdHexChanged();

private:
    using FfiFn = char* (*)(const char*);

    void        dispatchFfi(const QString& operation, std::function<QString()> fn);
    void        handleFfiResult(const QString& operation, const QString& result);
    QString     callFfi(FfiFn fn, const QJsonObject& args);
    QJsonObject baseArgs() const;

    QString m_walletPath;
    QString m_sequencerUrl;
    QString m_programIdHex;

    bool       m_busy      = false;
    QString    m_lastError;
    QString    m_lastTxHash;
    QVariantMap m_lastResult;
};

// Expected environment variable: LEZ_MULTISIG_PROGRAM_ID_HEX
