// Auto-generated by spel-client-gen --target logos-module. DO NOT EDIT.
// ISSUE: Generator emitted QQmlExtensionPlugin (wrong for Basecamp).
//        Basecamp modules use createWidget/destroyWidget (IComponent interface).
//        This file has been patched manually — see spel PR #209 for tracking.
#pragma once

#include <QObject>
#include <QWidget>

class LogosAPI;
class LezMultisigBackend;

class LezMultisigPlugin : public QObject {
    Q_OBJECT
public:
    explicit LezMultisigPlugin(QObject* parent = nullptr);
    ~LezMultisigPlugin() override;

    void    initLogos(LogosAPI* api);
    QWidget* createWidget(LogosAPI* api);
    void    destroyWidget(QWidget* widget);

private:
    LogosAPI*          m_api     = nullptr;
    LezMultisigBackend* m_backend = nullptr;
};
