[package]
name = "multisig_core"
version = "0.1.0"
edition = "2024"

[dependencies]
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee_core" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
borsh = "1.5.7"
spel-framework = { git = "https://github.com/logos-co/spel.git", rev = "4a1b89a0f64fc8ec66492b45514f54d705a1be90" }
